version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.0.0

commands:
  format-mapping:
    parameters:
      mapping:
        type: string
      output_file:
        type: string
        default: /tmp/format-mapping.conf
    steps:
      - run:
          name: Format mapping
          command: |
            mapping="<< parameters.mapping >>"

            trim() {
              local var="${1#"${1%%[![:space:]]*}"}"
              var="${var%"${var##*[![:space:]]}"}"
              echo "$var"
            }

            trimmed_mapping=$(trim "$mapping")

            echo "$trimmed_mapping" | awk '{print $1 " config_" $1 " \"" $2 "\""}' > << parameters.output_file >>

            cat << parameters.output_file >>
  extract-config-list:
    parameters:
      pipeline-parameters-json-file:
        type: string
        default: /tmp/pipeline-parameters.json
      config-list-path:
        default: /tmp/filtered-config-list.conf
        type: string
    steps:
      - run:
          name: Extract config list
          command: |
            INPUT_JSON_FILE=<<parameters.pipeline-parameters-json-file>>
            OUTPUT_FILE=<<parameters.config-list-path>>

            if [ ! -f "$INPUT_JSON_FILE" ]; then
              echo "Input JSON file does not exist: $INPUT_JSON_FILE"
              exit 1
            fi

            values=$(jq -r 'values[]' "$INPUT_JSON_FILE")

            values=$(echo "$values" | tr ',' '\n')

            echo "$values" | sort -u > "$OUTPUT_FILE"

            cat "$OUTPUT_FILE"

jobs:
  filter:
    executor: path-filtering/default
    steps:
      - checkout
      - format-mapping:
          mapping: |
            .* .circleci/pants_config.yml
            scripts/.* .circleci/pants_config.yml,.circleci/web_config.yml
            src/web/.* .circleci/web_config.yml
      - path-filtering/set-parameters:
          base-revision: main
          mapping: /tmp/format-mapping.conf
      - extract-config-list
      - run:
          name: debug
          command: |
            cat /tmp/format-mapping.conf

            echo "##############"

            cat /tmp/pipeline-parameters.json

            echo "##############"

            cat /tmp/filtered-config-list.conf
      - path-filtering/generate-config:
          config-list-path: /tmp/filtered-config-list.conf
          generated-config-path: .circleci/continue-config.yml
      - run:
          name: debug
          command: |
            cat .circleci/continue-config.yml
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml

workflows:
  generate-configs:
    jobs:
      - filter
      # - path-filtering/filter:
      #     mapping: |
      #       .* message "test" .circleci/pants_config.yml
      #       scripts/.* message "test" .circleci/pants_config.yml,.circleci/web_config.yml
      #       src/web/.* message "test" .circleci/web_config.yml