version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.0.0

commands:
  debug:
    steps:
      - run:
          command: |
            cat /tmp/pipeline-parameters.json
  extract-config-list:
    parameters:
      pipeline-parameters-json-file:
        type: string
        default: /tmp/pipeline-parameters.json
      config-list-path:
        type: string
        default: /tmp/filtered-config-list
    steps:
      - run:
          name: Extract config list
          command: |
            INPUT_JSON_FILE = <<parameters.pipeline-parameters-json-file>>
            OUTPUT_FILE = <<parameters.config-list-path>>

            if [ ! -f "$INPUT_JSON_FILE" ]; then
              echo "Input JSON file does not exist: $INPUT_JSON_FILE"
              exit 1
            fi

            # 使用 jq 提取 JSON 文件中的所有值，并逐行输出到输出文件中
            jq -r '.. | scalars' "$INPUT_JSON_FILE" > "$OUTPUT_FILE"

            echo "Values extracted from JSON file and saved to $OUTPUT_FILE"

            cat "$OUTPUT_FILE"
  set-continued-config:
    parameters:
      pipeline-parameters-json-file:
        type: string
        default: /tmp/pipeline-parameters.json
      configuration-path:
        type: string
        default: .circleci/continue.yml
      lookup-key:
        type: string
        description: key to look up the filepath for the next config
    steps:
      - run:
          name: Set next config as << parameters.configuration-path >>
          command: |
            # debug: confirm parameters json file

            cat << parameters.pipeline-parameters-json-file >>

            cp $(jq -r '.<< parameters.lookup-key >>' << parameters.pipeline-parameters-json-file >>) << parameters.configuration-path >>

            # debug: confirm next config
            cat << parameters.configuration-path >>
      - run:
          name: Pop << parameters.lookup-key >> key from << parameters.pipeline-parameters-json-file >>
          command: |
            jq 'del(.<< parameters.lookup-key >>)' << parameters.pipeline-parameters-json-file >> > params.json
            rm << parameters.pipeline-parameters-json-file >>
            cp params.json << parameters.pipeline-parameters-json-file >>

            # debug: confirm contents
            jq '.' << parameters.pipeline-parameters-json-file >>

jobs:
  filter:
    executor: path-filtering/default
    resource_class: small
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision: main
          mapping: |
            .* pants_config ".circleci/pants_config.yml"
            src/web/.* web_config ".circleci/web_config.yml"
      - debug
      - extract-config-list
      - path-filtering/generate-config
      # - set-continued-config:
      #     lookup-key: config
      - continuation/continue:
          configuration_path: .circleci/continue.yml
          parameters: /tmp/pipeline-parameters.json

workflows:
  setup:
    jobs:
      - filter
