version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.0.0

commands:
  debug:
    steps:
      - run:
          command: |
            cat /tmp/pipeline-parameters.json
  extract-config-list:
    parameters:
      pipeline-parameters-json-file:
        type: string
        default: /tmp/pipeline-parameters.json
      config-list-path:
        default: /tmp/filtered-config-list
        type: string
    steps:
      - run:
          name: Extract config list
          command: |
            INPUT_JSON_FILE = <<parameters.pipeline-parameters-json-file>>
            OUTPUT_FILE = <<parameters.config-list-path>>

            if [ ! -f "$INPUT_JSON_FILE" ]; then
              echo "Input JSON file does not exist: $INPUT_JSON_FILE"
              exit 1
            fi

            # 使用 jq 提取 JSON 文件中的所有值，并逐行输出到输出文件中
            jq -r '.. | scalars' "$INPUT_JSON_FILE" > "$OUTPUT_FILE"

            echo "Values extracted from JSON file and saved to $OUTPUT_FILE"

            cat "$OUTPUT_FILE"
  merge-config-list:
    parameters:
      config-list-path:
        default: /tmp/filtered-config-list
        type: string
      continue-config:
        type: string
        default: .circleci/continue-config.yml
    steps:
      - run:
          name: Merge config list
          command: |

            xargs -a "<<parameters.config-list-path>>" yq -y -s 'reduce .[] as $item ({}; . * $item)' | tee "<< parameters.continue-config >>"

            cat(<< parameters.continue-config >>)

jobs:
  filter:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install yq
          command: pip install yq
      - path-filtering/set-parameters:
          base-revision: main
          mapping: |
            .* pants_config ".circleci/pants_config.yml"
            src/web/.* web_config ".circleci/web_config.yml"
      - debug
      - extract-config-list
      - merge-config-list
      - continuation/continue:
          configuration_path: .circleci/continue.yml
          parameters: /tmp/pipeline-parameters.json

workflows:
  setup:
    jobs:
      - filter
