version: 2.1

parameters:
  message:
    type: string
    default: ''

jobs:
  pants_build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: echo << pipeline.parameters.message >>

workflows:
  build_workflow:
    jobs:
      - pants_build